### ISSUE TITLE
404 error when accessing the application

### ISSUE THREAD

**Issue by ntodorov** [linuxserver/docker-booksonic-air#3]
------------------------------

## Expected Behavior

I should be able to see the login screen of the freshly deployed booksonic-air.

## Current Behavior

I'm getting TomCat's 404 when accessing it with http://localhost:4040/

The container is running the latest tag.
The error page:

-----------------

HTTP Status 404 – Not Found
Type Status Report

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.37

-----------------

## Steps to Reproduce

1. Run Ubuntu 20.04 VM under Parallels
2. create folder booksonic under your home folder
3. create config, audiobooks, podcasts folders inside it
4. in the booksonic folder create docker-compose.yml file and past my config bellow
5. run docker-compose up
6 in browser hit HTTP://localhost:4040

## Environment
**OS:**  Main host MacOs Catalina, Parallels VM, Ubuntu 20.04    
**CPU architecture:** x86_64      
**How docker service was installed:**      

Inside of the Ubuntu VM I was following the steps from https://docs.docker.com/engine/install/ubuntu/
section "Install using the repository"

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up
`

My docker-compose.yml:
```
version: "2.1"
services:
  booksonic-air:
    image: linuxserver/booksonic-air
    container_name: booksonic-air
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CONTEXT_PATH=url-base
    volumes:
      - /home/parallels/projects/booksonic/config:/config
      - /home/parallels/projects/booksonic/audiobooks:/audiobooks
      - /home/parallels/projects/booksonic/podcasts:/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped
```

## Docker logs

See the attached logs.txt
[logs.txt](https://github.com/linuxserver/docker-booksonic-air/files/5301607/logs.txt)

## Additional info
I have tried the same steps directly on my MacOS with docker for Mac - same 404 error.
